services:
  banking-platform-eda:
    image: banking-platform-eda:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      BANKING_MYSQL_CONNECTION: ${BANKING_MYSQL_CONNECTION}
      BANKING_RABBITMQ_CONNECTION: ${BANKING_RABBITMQ_CONNECTION}